# Generated by Django 4.2.5 on 2023-09-10 14:05

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.TextField()),
                ("package_description", models.TextField(blank=True, null=True)),
                ("duration", models.IntegerField()),
                ("price", models.IntegerField()),
                ("accomodation_type", models.TextField(blank=True, null=True)),
                ("transportation_type", models.TextField(blank=True, null=True)),
                (
                    "meals",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=12,
                    ),
                ),
                ("tour_guide", models.BooleanField(default=True)),
                ("inclusions", models.TextField()),
                ("exclusions", models.TextField()),
                ("availability", models.DateField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.city"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.country"
            ),
        ),
    ]
