# Generated by Django 4.2.5 on 2023-09-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_packages_meals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packages",
            name="exclusions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="packages",
            name="inclusions",
            field=models.TextField(blank=True),
        ),
    ]
