# Generated by Django 4.2.5 on 2023-09-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
